export const pickups = [
"5% Voice AI",
"5% FCR",
"5% Digital Self Service",
"5% AI Assisted Support",
"5% Agentic AI Ops",
"5% Proactive Issue Resolution",

"10% Voice AI",
"10% FCR",
"10% Digital Self Service",
"10% AI Assisted Support",
"10% Agentic AI Ops",
"10% Proactive Issue Resolution",

"15% Voice AI",
"15% FCR",
"15% Digital Self Service",
"15% AI Assisted Support",
"15% Agentic AI Ops",
"15% Proactive Issue Resolution",

"20% Voice AI",
"20% FCR",
"20% Digital Self Service",
"20% AI Assisted Support",
"20% Agentic AI Ops",
"20% Proactive Issue Resolution",

"25% Voice AI",
"25% FCR",
"25% Digital Self Service",
"25% AI Assisted Support",
"25% Agentic AI Ops",
"25% Proactive Issue Resolution",

"30%  Voice AI",
"30% FCR",
"30%  Digital Self Service",
"30%  AI Assisted Support",
"30%  Agentic AI Ops",
"30%  Proactive Issue Resolution",

"35% Voice AI",
"35% FCR",
"35% Digital Self Service",
"35% AI Assisted Support",
"35% Agentic AI Ops",
"35% Proactive Issue Resolution",

"40%  Voice AI",
"40% FCR",
"40%  Digital Self Service",
"40%  AI Assisted Support",
"40%  Agentic AI Ops",
"40%  Proactive Issue Resolution",

"45% Voice AI",
"45% FCR",
"45% Digital Self Service",
"45% AI Assisted Support",
"45% Agentic AI Ops",
"45% Proactive Issue Resolution",

"50%  Voice AI",
"50% FCR",
"50%  Digital Self Service",
"50%  AI Assisted Support",
"50%  Agentic AI Ops",
"50%  Proactive Issue Resolution",

"55% Voice AI",
"55% FCR",
"55% Digital Self Service",
"55% AI Assisted Support",
"55% Agentic AI Ops",
"55% Proactive Issue Resolution",

"60%  Voice AI",
"60% FCR",
"60%  Digital Self Service",
"60%  AI Assisted Support",
"60%  Agentic AI Ops",
"60%  Proactive Issue Resolution",

"65% Voice AI",
"65% FCR",
"65% Digital Self Service",
"65% AI Assisted Support",
"65% Agentic AI Ops",
"65% Proactive Issue Resolution",

"70%  Voice AI",
"70% FCR",
"70%  Digital Self Service",
"70%  AI Assisted Support",
"70%  Agentic AI Ops",
"70%  Proactive Issue Resolution",

"75% Voice AI",
"75% FCR",
"75% Digital Self Service",
"75% AI Assisted Support",
"75% Agentic AI Ops",
"75% Proactive Issue Resolution",

"80%  Voice AI",
"80% FCR",
"80%  Digital Self Service",
"80%  AI Assisted Support",
"80%  Agentic AI Ops",
"80%  Proactive Issue Resolution",

"85% Voice AI",
"85% FCR",
"85% Digital Self Service",
"85% AI Assisted Support",
"85% Agentic AI Ops",
"85% Proactive Issue Resolution",

"90%  Voice AI",
"90% FCR",
"90%  Digital Self Service",
"90%  AI Assisted Support",
"90%  Agentic AI Ops",
"90%  Proactive Issue Resolution",

"95% Voice AI",
"95% FCR",
"95% Digital Self Service",
"95% AI Assisted Support",
"95% Agentic AI Ops",
"95% Proactive Issue Resolution",

"100%  Voice AI",
"100% FCR",
"100%  Digital Self Service",
"100%  AI Assisted Support",
"100%  Agentic AI Ops",
"100%  Proactive Issue Resolution",
]


export const outages = [
    "Competitor Fraud",
    "Scams",
    "Non compliance",
    "Downtime",
    'angry customers', 
    'missed SLAs', 
    'low synergy', 
    'no teamwork',
    "Competitor Fraud",
    "Scams",
    "Non compliance",
    "Downtime",
    'angry customers', 
    'missed SLAs', 
    'low synergy', 
    'no teamwork',
    "Competitor Fraud",
    "Scams",
    "Non compliance",
    "Downtime",
    'angry customers', 
    'missed SLAs', 
    'low synergy', 
    'no teamwork',
    "Competitor Fraud",
    "Scams",
    "Non compliance",
    "Downtime",
    'angry customers', 
    'missed SLAs', 
    'low synergy', 
    'no teamwork',
    "Competitor Fraud",
    "Scams",
    "Non compliance",
    "Downtime",
    'angry customers', 
    'missed SLAs', 
    'low synergy', 
    'no teamwork',
    "Competitor Fraud",
    "Scams",
    "Non compliance",
    "Downtime",
    'angry customers', 
    'missed SLAs', 
    'low synergy', 
    'no teamwork',
    "Competitor Fraud",
    "Scams",
    "Non compliance",
    "Downtime",
    'angry customers', 
    'missed SLAs', 
    'low synergy', 
    'no teamwork',
    "Competitor Fraud",
    "Scams",
    "Non compliance",
    "Downtime",
    'angry customers', 
    'missed SLAs', 
    'low synergy', 
    'no teamwork',
    "Competitor Fraud",
    "Scams",
    "Non compliance",
    "Downtime",
    'angry customers', 
    'missed SLAs', 
    'low synergy', 
    'no teamwork'
]