export const pickups = [
"10% Voice AI",
"10% FCR",
"10% Digital Self Service",
"10% AI Assisted Support",
"10% Agentic AI Ops",
"10% Proactive Issue Resolution",
"20% Voice AI",
"20% FCR",
"20% Digital Self Service",
"20% AI Assisted Support",
"20% Agentic AI Ops",
"20% Proactive Issue Resolution",
"30%  Voice AI",
"30% FCR",
"30%  Digital Self Service",
"30%  AI Assisted Support",
"30%  Agentic AI Ops",
"30%  Proactive Issue Resolution",
"40%  Voice AI",
"40% FCR",
"40%  Digital Self Service",
"40%  AI Assisted Support",
"40%  Agentic AI Ops",
"40%  Proactive Issue Resolution",
"50%  Voice AI",
"50% FCR",
"50%  Digital Self Service",
"50%  AI Assisted Support",
"50%  Agentic AI Ops",
"50%  Proactive Issue Resolution",
"60%  Voice AI",
"60% FCR",
"60%  Digital Self Service",
"60%  AI Assisted Support",
"60%  Agentic AI Ops",
"60%  Proactive Issue Resolution",
"70%  Voice AI",
"70% FCR",
"70%  Digital Self Service",
"70%  AI Assisted Support",
"70%  Agentic AI Ops",
"70%  Proactive Issue Resolution",
"80%  Voice AI",
"80% FCR",
"80%  Digital Self Service",
"80%  AI Assisted Support",
"80%  Agentic AI Ops",
"80%  Proactive Issue Resolution",
"90%  Voice AI",
"90% FCR",
"90%  Digital Self Service",
"90%  AI Assisted Support",
"90%  Agentic AI Ops",
"90%  Proactive Issue Resolution",
"100%  Voice AI",
"100% FCR",
"100%  Digital Self Service",
"100%  AI Assisted Support",
"100%  Agentic AI Ops",
"100%  Proactive Issue Resolution",
]


export const outages = [
    "Competitor Fraud",
    "Scams",
    "Non compliance",
    "Downtime",
]